apiVersion: v1
kind: Secret
metadata:
    name: mysecret
type: Opaque
data:
    username: ENC[AES256_GCM,data:ycMCsoMyidY=,iv:OrpvnaeKYMpRSWzjf0mWekXCG0QU1ptnW/2uPwDXfvw=,tag:OzQHnO9Abf7KK2MFY3p84w==,type:str]
    password: ENC[AES256_GCM,data:Uwdtz+lTOOAP6EOygm0S3w==,iv:XfKwJqZRLIsvwhY5oZMtgnMsMk1i0DYXNrhNyyBf5P8=,tag:oNSNozZNmxG3fk9reaGRug==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault:
        - vault_address: https://srdc-vault-staging.japaneast.cloudapp.azure.com
          engine_path: velocity-develop
          key_name: firstkey
          created_at: "2022-10-03T02:22:35Z"
          enc: vault:v1:bnYwRy+0/kdScRtU+IrQv1NVFdIAx0srX1AtxBuV72d38G+O3k69vPcnFYliN1vaPVTfrKzXVWAI06+Yt+IcYazMMia68HeYXQKB1z48RtVOgBfxBa0TZ07XnfvhFVUVIJWWAHd+NwEH+8mEc2U1CaJxY2qWbqGFzo2MeQC5jpO7EbdJWPekOBpcWxXiVoeF7mvzd4y8oVxtrsgC+p4pIcDBf7mHWtsFxCTgj8GmxGe0PUTNLeKNDDzHvVY3J06pi0BlX4qxO8+HOhsEJS257lfLx3fkN6fUO0FXdQfLKVv9DpU1y/ad5t3zd2wm3obrI/cK61vB+KHSmNJnm5KpkbbzpF/hfsfNBxT3sQOt0/T2YFucbysHO4oYAPxLXaWOKVikqRGyGQnAULC8Q2xjuSofxhaf+3G1ka3zVWXnDyrxqIBUzoIt3yAoABa+YRxEl2wvmHriIY6tfBUdMnvFdlQ0xSHkD+m0J/prSwS9gLYk5EMz+SdP16jbxS93NtcXWdv+76/Ny5sW9er79nwAQI4UgYUA/QxXYDlmiijJJdjfjugRSzILqtadswXwBl1sPdJ0Jl17NMrxEwg/dcxVlVmZPXgsi2b54iFsBuhLkv8JP656lSoe5VvbG4t3m6m8DLp3uO2zQ2E++MtU/KQHnbkDSM7eWp1vyh4v2TM72SY=
    age: []
    lastmodified: "2022-10-03T02:22:35Z"
    mac: ENC[AES256_GCM,data:L0TNZ3MDjcR6MKNxHy6BcrSGBqA43Iw0moAndbKamgeHJ8pV0Xtj+AxxhJP7O3QGV5fVDzcpeEIyIj/dxhrVfU1JGAdD2vrHbcbn7EtdY5fAM4LTgt/e8dKNGWmy7mTVY+UcjpMGrsytbUEEjCekEAel/rnvGsdz3Uv7aYr7zPg=,iv:gB0gpyl6NmqavzlhoFon11vuNnsQ2KWZ00nGv76dGto=,tag:bJTJ4B+rgb6+e1PBgnR24A==,type:str]
    pgp: []
    encrypted_regex: ^(username|password)$
    version: 3.7.3
